# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='indentcorp.platform.notid.v1alpha1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\"indentcorp.platform.notid.v1alpha1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n\x08Platform\x12?\n\x04name\x18\x01 \x01(\x0e\x32\x31.indentcorp.platform.notid.v1alpha1.Platform.Name\x12(\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x11\n\x04Name\x12\t\n\x05KAKAO\x10\x00\"?\n\x0eTargetSchedule\x12-\n\tsend_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"w\n\rRangeSchedule\x12\x33\n\x0fsend_start_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rsend_end_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xf9\x02\n\x0eMessageRequest\x12>\n\x08platform\x18\x01 \x01(\x0b\x32,.indentcorp.platform.notid.v1alpha1.Platform\x12)\n\x08metadata\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12M\n\x0ftarget_schedule\x18\x03 \x01(\x0b\x32\x32.indentcorp.platform.notid.v1alpha1.TargetScheduleH\x00\x12K\n\x0erange_schedule\x18\x04 \x01(\x0b\x32\x31.indentcorp.platform.notid.v1alpha1.RangeScheduleH\x00\x12\x18\n\x0estring_payload\x18\x05 \x01(\tH\x01\x12/\n\x0c\x64ict_payload\x18\x06 \x01(\x0b\x32\x17.google.protobuf.StructH\x01\x42\n\n\x08scheduleB\t\n\x07payload\"%\n\x0fMessageResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t2~\n\x07Message\x12s\n\x06\x63reate\x12\x32.indentcorp.platform.notid.v1alpha1.MessageRequest\x1a\x33.indentcorp.platform.notid.v1alpha1.MessageResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_PLATFORM_NAME = _descriptor.EnumDescriptor(
  name='Name',
  full_name='indentcorp.platform.notid.v1alpha1.Platform.Name',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KAKAO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=236,
  serialized_end=253,
)
_sym_db.RegisterEnumDescriptor(_PLATFORM_NAME)


_PLATFORM = _descriptor.Descriptor(
  name='Platform',
  full_name='indentcorp.platform.notid.v1alpha1.Platform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='indentcorp.platform.notid.v1alpha1.Platform.name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='context', full_name='indentcorp.platform.notid.v1alpha1.Platform.context', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLATFORM_NAME,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=253,
)


_TARGETSCHEDULE = _descriptor.Descriptor(
  name='TargetSchedule',
  full_name='indentcorp.platform.notid.v1alpha1.TargetSchedule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='send_time', full_name='indentcorp.platform.notid.v1alpha1.TargetSchedule.send_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=318,
)


_RANGESCHEDULE = _descriptor.Descriptor(
  name='RangeSchedule',
  full_name='indentcorp.platform.notid.v1alpha1.RangeSchedule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='send_start_time', full_name='indentcorp.platform.notid.v1alpha1.RangeSchedule.send_start_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='send_end_time', full_name='indentcorp.platform.notid.v1alpha1.RangeSchedule.send_end_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=439,
)


_MESSAGEREQUEST = _descriptor.Descriptor(
  name='MessageRequest',
  full_name='indentcorp.platform.notid.v1alpha1.MessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='platform', full_name='indentcorp.platform.notid.v1alpha1.MessageRequest.platform', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='indentcorp.platform.notid.v1alpha1.MessageRequest.metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_schedule', full_name='indentcorp.platform.notid.v1alpha1.MessageRequest.target_schedule', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range_schedule', full_name='indentcorp.platform.notid.v1alpha1.MessageRequest.range_schedule', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_payload', full_name='indentcorp.platform.notid.v1alpha1.MessageRequest.string_payload', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dict_payload', full_name='indentcorp.platform.notid.v1alpha1.MessageRequest.dict_payload', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='schedule', full_name='indentcorp.platform.notid.v1alpha1.MessageRequest.schedule',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='payload', full_name='indentcorp.platform.notid.v1alpha1.MessageRequest.payload',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=442,
  serialized_end=819,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='indentcorp.platform.notid.v1alpha1.MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_id', full_name='indentcorp.platform.notid.v1alpha1.MessageResponse.message_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=821,
  serialized_end=858,
)

_PLATFORM.fields_by_name['name'].enum_type = _PLATFORM_NAME
_PLATFORM.fields_by_name['context'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_PLATFORM_NAME.containing_type = _PLATFORM
_TARGETSCHEDULE.fields_by_name['send_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_RANGESCHEDULE.fields_by_name['send_start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_RANGESCHEDULE.fields_by_name['send_end_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_MESSAGEREQUEST.fields_by_name['platform'].message_type = _PLATFORM
_MESSAGEREQUEST.fields_by_name['metadata'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_MESSAGEREQUEST.fields_by_name['target_schedule'].message_type = _TARGETSCHEDULE
_MESSAGEREQUEST.fields_by_name['range_schedule'].message_type = _RANGESCHEDULE
_MESSAGEREQUEST.fields_by_name['dict_payload'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_MESSAGEREQUEST.oneofs_by_name['schedule'].fields.append(
  _MESSAGEREQUEST.fields_by_name['target_schedule'])
_MESSAGEREQUEST.fields_by_name['target_schedule'].containing_oneof = _MESSAGEREQUEST.oneofs_by_name['schedule']
_MESSAGEREQUEST.oneofs_by_name['schedule'].fields.append(
  _MESSAGEREQUEST.fields_by_name['range_schedule'])
_MESSAGEREQUEST.fields_by_name['range_schedule'].containing_oneof = _MESSAGEREQUEST.oneofs_by_name['schedule']
_MESSAGEREQUEST.oneofs_by_name['payload'].fields.append(
  _MESSAGEREQUEST.fields_by_name['string_payload'])
_MESSAGEREQUEST.fields_by_name['string_payload'].containing_oneof = _MESSAGEREQUEST.oneofs_by_name['payload']
_MESSAGEREQUEST.oneofs_by_name['payload'].fields.append(
  _MESSAGEREQUEST.fields_by_name['dict_payload'])
_MESSAGEREQUEST.fields_by_name['dict_payload'].containing_oneof = _MESSAGEREQUEST.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['Platform'] = _PLATFORM
DESCRIPTOR.message_types_by_name['TargetSchedule'] = _TARGETSCHEDULE
DESCRIPTOR.message_types_by_name['RangeSchedule'] = _RANGESCHEDULE
DESCRIPTOR.message_types_by_name['MessageRequest'] = _MESSAGEREQUEST
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Platform = _reflection.GeneratedProtocolMessageType('Platform', (_message.Message,), {
  'DESCRIPTOR' : _PLATFORM,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:indentcorp.platform.notid.v1alpha1.Platform)
  })
_sym_db.RegisterMessage(Platform)

TargetSchedule = _reflection.GeneratedProtocolMessageType('TargetSchedule', (_message.Message,), {
  'DESCRIPTOR' : _TARGETSCHEDULE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:indentcorp.platform.notid.v1alpha1.TargetSchedule)
  })
_sym_db.RegisterMessage(TargetSchedule)

RangeSchedule = _reflection.GeneratedProtocolMessageType('RangeSchedule', (_message.Message,), {
  'DESCRIPTOR' : _RANGESCHEDULE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:indentcorp.platform.notid.v1alpha1.RangeSchedule)
  })
_sym_db.RegisterMessage(RangeSchedule)

MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:indentcorp.platform.notid.v1alpha1.MessageRequest)
  })
_sym_db.RegisterMessage(MessageRequest)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:indentcorp.platform.notid.v1alpha1.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)



_MESSAGE = _descriptor.ServiceDescriptor(
  name='Message',
  full_name='indentcorp.platform.notid.v1alpha1.Message',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=860,
  serialized_end=986,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='indentcorp.platform.notid.v1alpha1.Message.create',
    index=0,
    containing_service=None,
    input_type=_MESSAGEREQUEST,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGE)

DESCRIPTOR.services_by_name['Message'] = _MESSAGE

# @@protoc_insertion_point(module_scope)
